# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'demo-auth-objc' do

pod 'sequencing-oauth-api-objc', '~> 1.0.1'

end

